### ISSUE TITLE
Mattermost does not load

### ISSUE THREAD

**Issue by sraupach** [Kopano-dev/mattermost-plugin-kopanowebmeetings#3] opened 2018-09-27 06:58 UTC
Hi.

I've got an issue when enabling the plugin (version 0.3.0, Mattermost Server 5.3.1).
If the plugin is enabled and my last open frame was a direct conversation (direct message) Mattermost does not load and return either an endless reload-logo or a white screen with the following error message in serverlog.

`{"level":"error","ts":1538031098.2145174,"caller":"web/context.go:60","msg":"msg: Uncaught TypeError: Cannot read property 'teammate_id' of undefined row: 36 col: 80813 stack: TypeError: Cannot read property 'teammate_id' of undefined url: https://<mydomain>/static/main.b6fa9dc5068008e05ea5.js","path":"/api/v4/logs","request_id":"kiiwngti3bfixrmqcr1eipbiwy","ip_addr":"<my IP>","user_id":"h4asn9zdk389i8gr9sefaeyzoc","method":"POST","err_where":"client","http_code":0,"err_details":""}`

If i disable the plugin everything works/reloads fine. This does only occur if your last active frame was in DMs. A restart of the app or restart browser does not solve the problem.

Regards
Steve

**Comment by fbartels** [comment] 2018-09-27 11:39
Hi @sraupach ,

can you share a bit more about your setup? I was unfortunately not able to reproduce your issue. I did the following steps:

- open Mattermost 5.3.1
- navigate to a private message
- close mattermost window
- reopen mattermost by going to its general url (say mattermost.domain.com)

For me Mattermost loads as expected.

There is one known issue though, that when you go into the system console and then back to your team there is a javascript error thrown (and you only see a grey page). This can be resolved by simply reloading Mattermost (ctrl + r). We knew if this error but rather wanted to have something compatible with 5.2+, than wait for a fix of this case.

**Comment by sraupach** [comment] 2018-09-27 12:33
hi @fbartels ,

ok, what you can try is communicate in a direct message and CRTL+R. I use the Mattermost App (Version 4.1.2 (4.1.2.46)). I will check if there is a newer client and try to reproduce again. Maybe i can make a small video or something like that(if it helps you).

Our Setup is pretty simple. NGINX -> Mattermost Cluster (2 nodes) -> DB-Server. In my testing i disabled one node to make sure that its not a cluster issue or something like that. NGINX only redirects to active/open mattermost server.

**Comment by sraupach** [comment] 2018-09-27 12:41
![bug-plugin](https://user-images.githubusercontent.com/8362597/46146603-79740e80-c263-11e8-93d7-a57f17eeecd7.png)

**Comment by fbartels** [comment] 2018-10-01 10:29
Hi @sraupach,

> what you can try is communicate in a direct message and CRTL+R.

yes, this is exactly what I tried, but at least in Chrome 69 this does not trigger an error. 

> I use the Mattermost App (Version 4.1.2 (4.1.2.46))

is that the Mattermost Desktop app?

EDIT:

> NGINX -> Mattermost Cluster (2 nodes) -> DB-Server

is that the Mattermost Enterprise Clustering functionality? Or just a simple standby system?

**Comment by sraupach** [comment] 2018-10-01 14:32
Hi @fbartels 

Ok, i am using the Mattermost Desktop App & Firefox 63.
Its a Mattermost Enterprise Cluster.

Regards
Steve

**Comment by fbartels** [comment] 2018-10-02 07:29
Hi @sraupach,

hmm maybe that then really is connected to the cluster setup. I've asked in https://pre-release.mattermost.com/core/pl/wjbpxs5i73d73nnoecrwbpywty if someone else with a cluster gets the same error and if there is an easy way to deploy such a cluster for dev purposes.

**Comment by fbartels** [comment] 2018-10-03 10:04
Hi @sraupach,

I have looked into the required steps to setup a cluster in Mattermost, and sadly it does not seem like this is something you can setup within a few minutes of time. I've checked with our current customers and none of them are planning to use our plugin with the HA functionality of Mattermost, which makes it hard for me to justify the work needed to further investigate this.

Seeing that you use the Mattermost Enterprise I guess you are planning to use this plugin in a corporate environment? If that is the case I would suggest to get in contact with us at sales@kopano.com to see if we can work out an agreement to further look into this issue on your behalf.

Until then I'm labeling this issue as "help wanted" to signal that even though this is not a priority for us, we will gladly review any outside pull requests that aim to fix this issue.

**Comment by sraupach** [comment] 2018-10-05 06:12
Hi @fbartels 
Actually the setup of a cluster is easy and doable in a few minutes for sure. Anyway..i am testing with one node disabled so the behavior of Mattermost is like a standalone installation. I am pretty sure that issue is not Cluster related.

The "cannot read property of teammate_id" error does occur if the plugin is disabled. I did not watch what you have changed to be compatible with Mattermost >5.2 but you are sure that there is no referenz to teammate_id?

thanks

**Comment by Felix-C** [comment] 2019-03-25 20:07
Same to me: TypeError: Cannot read property 'teammate_id' of undefined
Mattermost Desktop on Windows10

**Comment by fbartels** [comment] 2019-12-23 14:27
This plugin is now discontinued. We recommend to use [Kopano Meet](https://meet-app.io/) instead (which currently has no integration with Mattermost, though).

**Closed as completed by fbartels** 2019-12-23 14:27 UTC
Labels: help wanted
