### ISSUE TITLE
Plugin does not work with right sidebar

### ISSUE THREAD

**Issue by sraupach** [Kopano-dev/mattermost-plugin-kopanowebmeetings#1] opened 2018-06-26 07:18 UTC
If the Plugin is active in mattermost the expanded sidebar does not push the buttons to the middle of Mattermost. So if i have threaded conversation the upload & emoji Button from the main windows will be behind the sidebar.
Bottom
![grafik](https://user-images.githubusercontent.com/8362597/41895260-d46b6224-7921-11e8-90a9-5a6633242baa.png)

TOP
![grafik](https://user-images.githubusercontent.com/8362597/41895241-c51ed3a0-7921-11e8-8105-1f06efa64c1a.png)

**Comment by fbartels** [comment] 2018-06-26 08:27
Hi @sraupach,

thanks for your report. Which version of Mattermost and the plugin are you using? I have seen this happening before, but cannot reproduce it on my test system anymore (Mattermost 5.0.0 and kopanowebmeetings - 0.1.0-8-g9d69b3e)

**Comment by sraupach** [comment] 2018-06-26 08:29
I am using Mattermost 5.0.0 and Plugin 0.1.0-10-g3ff8631

**Comment by fbartels** [comment] 2018-06-26 09:33
Ok, gave it another spin and the overlapping only occurs when you actually search (so hit enter and have results displayed). I've created https://jira.kopano.io/browse/KWM-70 (ticket not public at the moment, because of the permissions on the project). Will update here once the issue is resolved.

**Comment by sraupach** [comment] 2018-06-26 10:53
On our environment the problem exsist without using the searchbar. Could you confirm that even your buttons on the main window are hidden? 
Good Case:
![grafik](https://user-images.githubusercontent.com/8362597/41906996-d1c4733a-793f-11e8-850a-4b9a2d3598c4.png)
Issue:
![grafik](https://user-images.githubusercontent.com/8362597/41907017-dea172c4-793f-11e8-8b2a-e6018136907d.png)

if i search the issue gets worse (i entered "s") :)
![grafik](https://user-images.githubusercontent.com/8362597/41907043-f2ac87a4-793f-11e8-86c8-b3db455a6ece.png)

**Comment by fbartels** [comment] 2018-06-26 11:10
ah, interesting. I thought that the search results overlay the chat messages was supposed to be like this, but it indeed does not happen when the webmeeting plugin is deactivated. will update the internal ticket in this regard.

**Comment by janwiesmann** [comment] 2018-07-23 19:11
Any update on this one?

**Comment by fbartels** [comment] 2018-07-24 11:47
Hi @janwiesmann,

this issue should have been resolved with https://github.com/Kopano-dev/mattermost-plugin-kopanowebmeetings/commit/69d5ee0a4b7cd602ecab75a3ccb2d078f2b38fb8. I just made a small repro test with an old 0.1.0 version and the latest and was not able to reproduce it anymore after updating to the lastest package.

**Comment by fbartels** [comment] 2018-07-25 10:19
We had a bit of confusion here, we at first it seemed this is fixed, but we actually still need to put some work into this. reopening.

**Comment by janwiesmann** [comment] 2018-08-08 10:12
@fbartels I'm curious: What's your timeline for resolving this issue?

**Comment by fbartels** [comment] 2018-08-09 07:27
Hi @janwiesmann ,

its on our todo list, but since we do not have any customer running this plugin until now it has no high priority for us. Mattermost is planning some [breaking changes to the plugin architecture](https://forum.mattermost.org/t/plugin-system-upgrade-in-mattermost-5-2/5498) for the 5.2 release, maybe that could be a good opportunity to solve this as well.

If you are using the plugin in a commercial context it may also be an idea to get in [contact with our sales team](https://kopano.com/contact/), so we can reorganise priorities for this.

**Comment by fbartels** [comment] 2018-09-19 14:02
Hi @sraupach,

the plugin just got updated for Mattermost >=5.2 compatibility. While there are still some known issues (ringtone does not load and after the plugin has been enabled there is a javascript error that forces users to reload mattermost), the original error of this thread cannot be observed anymore.

**Closed as completed by fbartels** 2018-09-19 14:02 UTC
